# inflator.toml syntax documentation: https://github.com/faretek1/inflator#inflator
name = "geo2d"
version = "v1.0.0"
username = "FAReTek1"

[dependencies]
math = "https://github.com/FAReTek1/math"
vec2 = "https://github.com/FAReTek1/vec2"
